export const seedId = (suffix: number) =>
  `00000000-0000-4000-8000-${String(suffix).padStart(12, "0")}`;

export const fixtureId = (group: number, suffix: number) =>
  `${String(group).padStart(8, "0")}-0000-4000-8000-${String(suffix).padStart(12, "0")}`;

export const sampleIds = {
  workspace: seedId(1),
  types: {
    franchise: seedId(101),
    series: seedId(102),
    season: seedId(103),
    episode: seedId(104),
    movie: seedId(105),
    special: seedId(106),
    live_event: seedId(107),
    sports_event: seedId(108),
  },
  platforms: {
    peacock: seedId(201),
    netflix: seedId(202),
    hulu: seedId(203),
    prime: seedId(204),
    nbc: seedId(205),
    max: seedId(206),
    disney: seedId(207),
    apple: seedId(208),
  },
  sources: {
    peacock: seedId(401),
    netflix: seedId(402),
    hulu: seedId(403),
    prime: seedId(404),
    nbc: seedId(405),
    max: seedId(406),
    disney: seedId(407),
    apple: seedId(408),
  },
  runs: {
    peacock: seedId(501),
    netflix: seedId(502),
    hulu: seedId(503),
    prime: seedId(504),
    nbc: seedId(505),
    max: seedId(506),
    disney: seedId(507),
    apple: seedId(508),
  },
} as const;

export type SampleContentKey =
  | "officeUs"
  | "officeUk"
  | "parks"
  | "oppenheimer"
  | "dune2021"
  | "dune1984"
  | "bladeRunner"
  | "bladeRunner2049"
  | "theBear"
  | "shogun"
  | "theCrown"
  | "parasite"
  | "everythingEverywhere"
  | "lastOfUs"
  | "arrival"
  | "fargoFilm"
  | "fargoSeries"
  | "batman2022"
  | "batman1989"
  | "madMax"
  | "succession"
  | "severance"
  | "moana"
  | "moana2";

export interface SampleTitle {
  key: SampleContentKey;
  id: string;
  title: string;
  originalTitle?: string;
  type: "movie" | "series";
  releaseYear: number;
  country: string;
  language: string;
  runtimeMinutes?: number;
  status: "released" | "returning" | "ended";
  accent: string;
  genres: string[];
  synopsis: string;
  aliases: Array<{
    title: string;
    type: "official" | "alias" | "localized" | "working";
    country: string;
    language?: string;
    primary?: boolean;
  }>;
  imdb: string;
  tmdb: string;
  tmdbType: "movie" | "tv";
}

export const sampleTitles: SampleTitle[] = [
  {
    key: "officeUs",
    id: seedId(301),
    title: "The Office",
    type: "series",
    releaseYear: 2005,
    country: "US",
    language: "en",
    status: "ended",
    accent: "#315f49",
    genres: ["Comedy", "Workplace"],
    synopsis:
      "A mockumentary following the everyday lives of employees at a regional paper company.",
    aliases: [
      { title: "The Office", type: "official", country: "US", primary: true },
      { title: "The Office (U.S.)", type: "alias", country: "US" },
      { title: "Office, The", type: "alias", country: "US" },
      { title: "The Office (2005)", type: "alias", country: "US" },
    ],
    imdb: "tt0386676",
    tmdb: "2316",
    tmdbType: "tv",
  },
  {
    key: "officeUk",
    id: seedId(302),
    title: "The Office",
    type: "series",
    releaseYear: 2001,
    country: "GB",
    language: "en",
    status: "ended",
    accent: "#675a45",
    genres: ["Comedy", "Workplace"],
    synopsis:
      "A documentary crew records the awkward routines of an English paper merchant and its staff.",
    aliases: [
      { title: "The Office", type: "official", country: "GB", primary: true },
      { title: "The Office (UK)", type: "alias", country: "GB" },
      { title: "The Office UK", type: "alias", country: "GB" },
    ],
    imdb: "tt0290978",
    tmdb: "2996",
    tmdbType: "tv",
  },
  {
    key: "parks",
    id: seedId(303),
    title: "Parks and Recreation",
    type: "series",
    releaseYear: 2009,
    country: "US",
    language: "en",
    status: "ended",
    accent: "#b76e2e",
    genres: ["Comedy", "Workplace"],
    synopsis:
      "Optimistic public servants work to make their fictional Indiana town a better place.",
    aliases: [
      {
        title: "Parks and Recreation",
        type: "official",
        country: "US",
        primary: true,
      },
      { title: "Parks & Rec", type: "alias", country: "US" },
    ],
    imdb: "tt1266020",
    tmdb: "8592",
    tmdbType: "tv",
  },
  {
    key: "oppenheimer",
    id: seedId(304),
    title: "Oppenheimer",
    type: "movie",
    releaseYear: 2023,
    country: "US",
    language: "en",
    runtimeMinutes: 180,
    status: "released",
    accent: "#b64e26",
    genres: ["Drama", "History"],
    synopsis:
      "The story of J. Robert Oppenheimer and the scientific, political, and moral consequences of the atomic bomb.",
    aliases: [
      {
        title: "Oppenheimer",
        type: "official",
        country: "US",
        primary: true,
      },
    ],
    imdb: "tt15398776",
    tmdb: "872585",
    tmdbType: "movie",
  },
  {
    key: "dune2021",
    id: seedId(305),
    title: "Dune",
    type: "movie",
    releaseYear: 2021,
    country: "US",
    language: "en",
    runtimeMinutes: 155,
    status: "released",
    accent: "#b77837",
    genres: ["Science fiction", "Adventure"],
    synopsis:
      "A gifted heir travels to the most dangerous planet in the universe to protect his family and people.",
    aliases: [
      { title: "Dune", type: "official", country: "US", primary: true },
      { title: "Dune: Part One", type: "alias", country: "US" },
      { title: "Dune (2021)", type: "alias", country: "US" },
    ],
    imdb: "tt1160419",
    tmdb: "438631",
    tmdbType: "movie",
  },
  {
    key: "dune1984",
    id: seedId(306),
    title: "Dune",
    type: "movie",
    releaseYear: 1984,
    country: "US",
    language: "en",
    runtimeMinutes: 137,
    status: "released",
    accent: "#826145",
    genres: ["Science fiction", "Adventure"],
    synopsis:
      "A young nobleman becomes entangled in a battle for control of a desert planet and its precious resource.",
    aliases: [
      { title: "Dune", type: "official", country: "US", primary: true },
      { title: "Dune (1984)", type: "alias", country: "US" },
    ],
    imdb: "tt0087182",
    tmdb: "841",
    tmdbType: "movie",
  },
  {
    key: "bladeRunner",
    id: seedId(307),
    title: "Blade Runner",
    type: "movie",
    releaseYear: 1982,
    country: "US",
    language: "en",
    runtimeMinutes: 117,
    status: "released",
    accent: "#ab4450",
    genres: ["Science fiction", "Thriller"],
    synopsis:
      "A weary detective hunts bioengineered fugitives in a rain-soaked future Los Angeles.",
    aliases: [
      {
        title: "Blade Runner",
        type: "official",
        country: "US",
        primary: true,
      },
      {
        title: "Blade Runner: The Final Cut",
        type: "alias",
        country: "US",
      },
    ],
    imdb: "tt0083658",
    tmdb: "78",
    tmdbType: "movie",
  },
  {
    key: "bladeRunner2049",
    id: seedId(308),
    title: "Blade Runner 2049",
    type: "movie",
    releaseYear: 2017,
    country: "US",
    language: "en",
    runtimeMinutes: 164,
    status: "released",
    accent: "#ca6639",
    genres: ["Science fiction", "Drama"],
    synopsis:
      "A new blade runner uncovers a secret that leads him to a former LAPD officer missing for decades.",
    aliases: [
      {
        title: "Blade Runner 2049",
        type: "official",
        country: "US",
        primary: true,
      },
      { title: "Blade Runner: 2049", type: "alias", country: "US" },
    ],
    imdb: "tt1856101",
    tmdb: "335984",
    tmdbType: "movie",
  },
  {
    key: "theBear",
    id: seedId(309),
    title: "The Bear",
    type: "series",
    releaseYear: 2022,
    country: "US",
    language: "en",
    status: "returning",
    accent: "#245b83",
    genres: ["Drama", "Comedy"],
    synopsis:
      "A young chef returns home to run his family’s sandwich shop and transform its chaotic kitchen.",
    aliases: [
      { title: "The Bear", type: "official", country: "US", primary: true },
      { title: "Bear, The", type: "alias", country: "US" },
    ],
    imdb: "tt14452776",
    tmdb: "136315",
    tmdbType: "tv",
  },
  {
    key: "shogun",
    id: seedId(310),
    title: "Shōgun",
    type: "series",
    releaseYear: 2024,
    country: "US",
    language: "en",
    status: "returning",
    accent: "#9e3232",
    genres: ["Drama", "History"],
    synopsis:
      "Political rivals and a shipwrecked English navigator collide in feudal Japan.",
    aliases: [
      { title: "Shōgun", type: "official", country: "US", primary: true },
      { title: "Shogun", type: "alias", country: "US" },
      { title: "SHŌGUN", type: "alias", country: "US" },
    ],
    imdb: "tt2788316",
    tmdb: "126308",
    tmdbType: "tv",
  },
  {
    key: "theCrown",
    id: seedId(311),
    title: "The Crown",
    type: "series",
    releaseYear: 2016,
    country: "GB",
    language: "en",
    status: "ended",
    accent: "#6d5c91",
    genres: ["Drama", "History"],
    synopsis:
      "A chronicle of Queen Elizabeth II’s reign and the personal and political events around the monarchy.",
    aliases: [
      { title: "The Crown", type: "official", country: "GB", primary: true },
      { title: "Crown, The", type: "alias", country: "GB" },
    ],
    imdb: "tt4786824",
    tmdb: "65494",
    tmdbType: "tv",
  },
  {
    key: "parasite",
    id: seedId(312),
    title: "Parasite",
    originalTitle: "기생충",
    type: "movie",
    releaseYear: 2019,
    country: "KR",
    language: "ko",
    runtimeMinutes: 132,
    status: "released",
    accent: "#3f7257",
    genres: ["Drama", "Thriller"],
    synopsis:
      "A struggling family gradually inserts itself into the household of a wealthy family.",
    aliases: [
      { title: "Parasite", type: "official", country: "US", primary: true },
      {
        title: "기생충",
        type: "localized",
        country: "KR",
        language: "ko",
      },
      { title: "Gisaengchung", type: "alias", country: "KR" },
    ],
    imdb: "tt6751668",
    tmdb: "496243",
    tmdbType: "movie",
  },
  {
    key: "everythingEverywhere",
    id: seedId(313),
    title: "Everything Everywhere All at Once",
    type: "movie",
    releaseYear: 2022,
    country: "US",
    language: "en",
    runtimeMinutes: 140,
    status: "released",
    accent: "#8d4d8c",
    genres: ["Science fiction", "Comedy"],
    synopsis:
      "An overwhelmed laundromat owner is swept into a wild multiversal struggle.",
    aliases: [
      {
        title: "Everything Everywhere All at Once",
        type: "official",
        country: "US",
        primary: true,
      },
      { title: "EEAAO", type: "alias", country: "US" },
    ],
    imdb: "tt6710474",
    tmdb: "545611",
    tmdbType: "movie",
  },
  {
    key: "lastOfUs",
    id: seedId(314),
    title: "The Last of Us",
    type: "series",
    releaseYear: 2023,
    country: "US",
    language: "en",
    status: "returning",
    accent: "#596347",
    genres: ["Drama", "Science fiction"],
    synopsis:
      "A hardened survivor escorts a teenager across a post-pandemic United States.",
    aliases: [
      {
        title: "The Last of Us",
        type: "official",
        country: "US",
        primary: true,
      },
      { title: "Last of Us, The", type: "alias", country: "US" },
    ],
    imdb: "tt3581920",
    tmdb: "100088",
    tmdbType: "tv",
  },
  {
    key: "arrival",
    id: seedId(315),
    title: "Arrival",
    type: "movie",
    releaseYear: 2016,
    country: "US",
    language: "en",
    runtimeMinutes: 116,
    status: "released",
    accent: "#4f6f7c",
    genres: ["Science fiction", "Drama"],
    synopsis:
      "A linguist works with the military to communicate with visitors whose craft have appeared around the world.",
    aliases: [
      { title: "Arrival", type: "official", country: "US", primary: true },
      { title: "Story of Your Life", type: "working", country: "US" },
    ],
    imdb: "tt2543164",
    tmdb: "329865",
    tmdbType: "movie",
  },
  {
    key: "fargoFilm",
    id: seedId(316),
    title: "Fargo",
    type: "movie",
    releaseYear: 1996,
    country: "US",
    language: "en",
    runtimeMinutes: 98,
    status: "released",
    accent: "#6f8ba3",
    genres: ["Crime", "Drama"],
    synopsis:
      "A desperate car dealer’s clumsy kidnapping scheme collides with a persistent police chief.",
    aliases: [
      { title: "Fargo", type: "official", country: "US", primary: true },
      { title: "Fargo (1996)", type: "alias", country: "US" },
    ],
    imdb: "tt0116282",
    tmdb: "275",
    tmdbType: "movie",
  },
  {
    key: "fargoSeries",
    id: seedId(317),
    title: "Fargo",
    type: "series",
    releaseYear: 2014,
    country: "US",
    language: "en",
    status: "returning",
    accent: "#745752",
    genres: ["Crime", "Drama"],
    synopsis:
      "Interconnected crime stories unfold across the American Midwest in an anthology series.",
    aliases: [
      { title: "Fargo", type: "official", country: "US", primary: true },
      { title: "Fargo (TV)", type: "alias", country: "US" },
    ],
    imdb: "tt2802850",
    tmdb: "60622",
    tmdbType: "tv",
  },
  {
    key: "batman2022",
    id: seedId(318),
    title: "The Batman",
    type: "movie",
    releaseYear: 2022,
    country: "US",
    language: "en",
    runtimeMinutes: 176,
    status: "released",
    accent: "#8c2d30",
    genres: ["Crime", "Action"],
    synopsis:
      "A young vigilante follows a trail of corruption while pursuing a serial killer in Gotham City.",
    aliases: [
      { title: "The Batman", type: "official", country: "US", primary: true },
      { title: "Batman, The", type: "alias", country: "US" },
    ],
    imdb: "tt1877830",
    tmdb: "414906",
    tmdbType: "movie",
  },
  {
    key: "batman1989",
    id: seedId(319),
    title: "Batman",
    type: "movie",
    releaseYear: 1989,
    country: "US",
    language: "en",
    runtimeMinutes: 126,
    status: "released",
    accent: "#353846",
    genres: ["Action", "Fantasy"],
    synopsis:
      "Gotham’s masked vigilante confronts a theatrical criminal mastermind.",
    aliases: [
      { title: "Batman", type: "official", country: "US", primary: true },
      { title: "Batman (1989)", type: "alias", country: "US" },
    ],
    imdb: "tt0096895",
    tmdb: "268",
    tmdbType: "movie",
  },
  {
    key: "madMax",
    id: seedId(320),
    title: "Mad Max: Fury Road",
    type: "movie",
    releaseYear: 2015,
    country: "AU",
    language: "en",
    runtimeMinutes: 120,
    status: "released",
    accent: "#b55427",
    genres: ["Action", "Science fiction"],
    synopsis:
      "Rebels flee a tyrant across a scorched wasteland in a roaring convoy.",
    aliases: [
      {
        title: "Mad Max: Fury Road",
        type: "official",
        country: "AU",
        primary: true,
      },
      { title: "Mad Max Fury Road", type: "alias", country: "US" },
    ],
    imdb: "tt1392190",
    tmdb: "76341",
    tmdbType: "movie",
  },
  {
    key: "succession",
    id: seedId(321),
    title: "Succession",
    type: "series",
    releaseYear: 2018,
    country: "US",
    language: "en",
    status: "ended",
    accent: "#756b57",
    genres: ["Drama", "Comedy"],
    synopsis:
      "A powerful media family fights over control of its empire as its patriarch’s health declines.",
    aliases: [
      { title: "Succession", type: "official", country: "US", primary: true },
    ],
    imdb: "tt7660850",
    tmdb: "76331",
    tmdbType: "tv",
  },
  {
    key: "severance",
    id: seedId(322),
    title: "Severance",
    type: "series",
    releaseYear: 2022,
    country: "US",
    language: "en",
    status: "returning",
    accent: "#295e70",
    genres: ["Drama", "Mystery"],
    synopsis:
      "Office workers undergo a procedure that divides their work memories from their personal lives.",
    aliases: [
      { title: "Severance", type: "official", country: "US", primary: true },
      { title: "Severance (2022)", type: "alias", country: "US" },
    ],
    imdb: "tt11280740",
    tmdb: "95396",
    tmdbType: "tv",
  },
  {
    key: "moana",
    id: seedId(323),
    title: "Moana",
    type: "movie",
    releaseYear: 2016,
    country: "US",
    language: "en",
    runtimeMinutes: 107,
    status: "released",
    accent: "#16829a",
    genres: ["Animation", "Adventure"],
    synopsis:
      "A wayfinder sails across the ocean to restore the heart of a goddess and save her island.",
    aliases: [
      { title: "Moana", type: "official", country: "US", primary: true },
      { title: "Vaiana", type: "localized", country: "DE" },
      { title: "Oceania", type: "localized", country: "IT" },
    ],
    imdb: "tt3521164",
    tmdb: "277834",
    tmdbType: "movie",
  },
  {
    key: "moana2",
    id: seedId(324),
    title: "Moana 2",
    type: "movie",
    releaseYear: 2024,
    country: "US",
    language: "en",
    runtimeMinutes: 100,
    status: "released",
    accent: "#2375a1",
    genres: ["Animation", "Adventure"],
    synopsis:
      "Moana answers a call from her ancestors and voyages into dangerous, long-lost waters.",
    aliases: [
      { title: "Moana 2", type: "official", country: "US", primary: true },
      { title: "Vaiana 2", type: "localized", country: "DE" },
    ],
    imdb: "tt13622970",
    tmdb: "1241982",
    tmdbType: "movie",
  },
];

export type SampleSourceKey = keyof typeof sampleIds.sources;

export const samplePlatforms = [
  {
    key: "peacock",
    id: sampleIds.platforms.peacock,
    name: "Peacock",
    slug: "peacock",
    type: "streaming",
    color: "#2563eb",
  },
  {
    key: "netflix",
    id: sampleIds.platforms.netflix,
    name: "Netflix",
    slug: "netflix",
    type: "streaming",
    color: "#e11d48",
  },
  {
    key: "hulu",
    id: sampleIds.platforms.hulu,
    name: "Hulu",
    slug: "hulu",
    type: "streaming",
    color: "#059669",
  },
  {
    key: "prime",
    id: sampleIds.platforms.prime,
    name: "Prime Video",
    slug: "prime-video",
    type: "streaming",
    color: "#0891b2",
  },
  {
    key: "nbc",
    id: sampleIds.platforms.nbc,
    name: "Linear NBC",
    slug: "linear-nbc",
    type: "linear",
    color: "#7c3aed",
  },
  {
    key: "max",
    id: sampleIds.platforms.max,
    name: "Max",
    slug: "max",
    type: "streaming",
    color: "#4f46e5",
  },
  {
    key: "disney",
    id: sampleIds.platforms.disney,
    name: "Disney+",
    slug: "disney-plus",
    type: "streaming",
    color: "#0369a1",
  },
  {
    key: "apple",
    id: sampleIds.platforms.apple,
    name: "Apple TV+",
    slug: "apple-tv-plus",
    type: "streaming",
    color: "#475569",
  },
] as const;

export const sampleSources = [
  {
    key: "peacock",
    id: sampleIds.sources.peacock,
    runId: sampleIds.runs.peacock,
    platformKey: "peacock",
    name: "Peacock Internal Feed",
    type: "api",
  },
  {
    key: "netflix",
    id: sampleIds.sources.netflix,
    runId: sampleIds.runs.netflix,
    platformKey: "netflix",
    name: "Netflix Partner Export",
    type: "partner_feed",
  },
  {
    key: "hulu",
    id: sampleIds.sources.hulu,
    runId: sampleIds.runs.hulu,
    platformKey: "hulu",
    name: "Hulu CSV Upload",
    type: "csv_upload",
  },
  {
    key: "prime",
    id: sampleIds.sources.prime,
    runId: sampleIds.runs.prime,
    platformKey: "prime",
    name: "Prime Video Catalog",
    type: "partner_feed",
  },
  {
    key: "nbc",
    id: sampleIds.sources.nbc,
    runId: sampleIds.runs.nbc,
    platformKey: "nbc",
    name: "NBC Broadcast Schedule",
    type: "database",
  },
  {
    key: "max",
    id: sampleIds.sources.max,
    runId: sampleIds.runs.max,
    platformKey: "max",
    name: "Max Content Graph",
    type: "api",
  },
  {
    key: "disney",
    id: sampleIds.sources.disney,
    runId: sampleIds.runs.disney,
    platformKey: "disney",
    name: "Disney+ Availability Feed",
    type: "partner_feed",
  },
  {
    key: "apple",
    id: sampleIds.sources.apple,
    runId: sampleIds.runs.apple,
    platformKey: "apple",
    name: "Apple TV+ Metadata Sync",
    type: "api",
  },
] as const;

export interface SampleEntity {
  id: string;
  contentKey: SampleContentKey;
  sourceKey: SampleSourceKey;
  nativeId: string;
  title: string;
  year?: number | null;
  country?: string | null;
  type?: "movie" | "series";
  confidence: number;
  method: "external_id" | "automatic" | "seed";
  metricBase: number;
}

export const sampleEntities: SampleEntity[] = [
  {
    id: seedId(601),
    contentKey: "officeUs",
    sourceKey: "peacock",
    nativeId: "pk-office-us",
    title: "The Office (2005)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 118_000,
  },
  {
    id: seedId(602),
    contentKey: "officeUs",
    sourceKey: "netflix",
    nativeId: "nf-44821",
    title: "Office, The",
    confidence: 0.98,
    method: "automatic",
    metricBase: 94_000,
  },
  {
    id: seedId(604),
    contentKey: "officeUk",
    sourceKey: "hulu",
    nativeId: "hu-office-uk",
    title: "The Office (UK)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 34_000,
  },
  {
    id: seedId(605),
    contentKey: "parks",
    sourceKey: "peacock",
    nativeId: "pk-parks",
    title: "Parks & Rec",
    confidence: 0.98,
    method: "automatic",
    metricBase: 61_000,
  },
  {
    id: seedId(606),
    contentKey: "oppenheimer",
    sourceKey: "netflix",
    nativeId: "nf-oppenheimer",
    title: "Oppenheimer",
    confidence: 1,
    method: "external_id",
    metricBase: 78_000,
  },
  {
    id: seedId(608),
    contentKey: "dune2021",
    sourceKey: "max",
    nativeId: "max-dune-part-one",
    title: "DUNE: PART ONE",
    confidence: 1,
    method: "external_id",
    metricBase: 86_000,
  },
  {
    id: seedId(609),
    contentKey: "dune2021",
    sourceKey: "prime",
    nativeId: "pv-dune-2021",
    title: "Dune (2021)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 47_000,
  },
  {
    id: seedId(610),
    contentKey: "dune1984",
    sourceKey: "max",
    nativeId: "max-dune-1984",
    title: "Dune",
    confidence: 0.97,
    method: "automatic",
    metricBase: 17_000,
  },
  {
    id: seedId(611),
    contentKey: "bladeRunner",
    sourceKey: "max",
    nativeId: "max-blade-runner-final-cut",
    title: "Blade Runner: The Final Cut",
    confidence: 1,
    method: "external_id",
    metricBase: 29_000,
  },
  {
    id: seedId(612),
    contentKey: "bladeRunner",
    sourceKey: "prime",
    nativeId: "pv-blade-runner",
    title: "Blade Runner",
    confidence: 0.97,
    method: "automatic",
    metricBase: 22_000,
  },
  {
    id: seedId(613),
    contentKey: "bladeRunner2049",
    sourceKey: "netflix",
    nativeId: "nf-br-2049",
    title: "Blade Runner: 2049",
    confidence: 0.98,
    method: "automatic",
    metricBase: 42_000,
  },
  {
    id: seedId(614),
    contentKey: "theBear",
    sourceKey: "hulu",
    nativeId: "hu-the-bear",
    title: "Bear, The",
    confidence: 0.98,
    method: "automatic",
    metricBase: 105_000,
  },
  {
    id: seedId(615),
    contentKey: "theBear",
    sourceKey: "disney",
    nativeId: "dp-the-bear",
    title: "The Bear (2022)",
    confidence: 1,
    method: "external_id",
    metricBase: 49_000,
  },
  {
    id: seedId(616),
    contentKey: "shogun",
    sourceKey: "hulu",
    nativeId: "hu-shogun-2024",
    title: "Shogun",
    confidence: 0.98,
    method: "automatic",
    metricBase: 91_000,
  },
  {
    id: seedId(617),
    contentKey: "shogun",
    sourceKey: "disney",
    nativeId: "dp-shogun",
    title: "SHŌGUN",
    confidence: 1,
    method: "external_id",
    metricBase: 58_000,
  },
  {
    id: seedId(618),
    contentKey: "theCrown",
    sourceKey: "netflix",
    nativeId: "nf-crown",
    title: "Crown, The",
    confidence: 0.98,
    method: "automatic",
    metricBase: 69_000,
  },
  {
    id: seedId(619),
    contentKey: "parasite",
    sourceKey: "hulu",
    nativeId: "hu-parasite",
    title: "Parasite",
    confidence: 1,
    method: "external_id",
    metricBase: 38_000,
  },
  {
    id: seedId(620),
    contentKey: "parasite",
    sourceKey: "prime",
    nativeId: "pv-gisaengchung",
    title: "기생충",
    confidence: 0.97,
    method: "automatic",
    metricBase: 26_000,
  },
  {
    id: seedId(621),
    contentKey: "everythingEverywhere",
    sourceKey: "prime",
    nativeId: "pv-eeaao",
    title: "EEAAO",
    confidence: 1,
    method: "external_id",
    metricBase: 64_000,
  },
  {
    id: seedId(622),
    contentKey: "everythingEverywhere",
    sourceKey: "netflix",
    nativeId: "nf-everything-everywhere",
    title: "Everything Everywhere All At Once",
    confidence: 0.99,
    method: "automatic",
    metricBase: 53_000,
  },
  {
    id: seedId(623),
    contentKey: "lastOfUs",
    sourceKey: "max",
    nativeId: "max-tlou",
    title: "Last of Us, The",
    confidence: 1,
    method: "external_id",
    metricBase: 112_000,
  },
  {
    id: seedId(624),
    contentKey: "arrival",
    sourceKey: "prime",
    nativeId: "pv-arrival-2016",
    title: "Arrival (2016)",
    confidence: 1,
    method: "external_id",
    metricBase: 31_000,
  },
  {
    id: seedId(625),
    contentKey: "arrival",
    sourceKey: "netflix",
    nativeId: "nf-arrival",
    title: "Arrival",
    confidence: 0.97,
    method: "automatic",
    metricBase: 28_000,
  },
  {
    id: seedId(626),
    contentKey: "fargoFilm",
    sourceKey: "prime",
    nativeId: "pv-fargo-1996",
    title: "Fargo (1996)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 19_000,
  },
  {
    id: seedId(627),
    contentKey: "fargoSeries",
    sourceKey: "hulu",
    nativeId: "hu-fargo-tv",
    title: "Fargo (TV)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 57_000,
  },
  {
    id: seedId(628),
    contentKey: "batman2022",
    sourceKey: "max",
    nativeId: "max-the-batman",
    title: "Batman, The",
    confidence: 1,
    method: "external_id",
    metricBase: 83_000,
  },
  {
    id: seedId(629),
    contentKey: "batman1989",
    sourceKey: "max",
    nativeId: "max-batman-1989",
    title: "Batman (1989)",
    confidence: 0.99,
    method: "automatic",
    metricBase: 23_000,
  },
  {
    id: seedId(630),
    contentKey: "batman1989",
    sourceKey: "prime",
    nativeId: "pv-batman",
    title: "Batman",
    confidence: 1,
    method: "external_id",
    metricBase: 16_000,
  },
  {
    id: seedId(631),
    contentKey: "madMax",
    sourceKey: "max",
    nativeId: "max-fury-road",
    title: "Mad Max Fury Road",
    confidence: 0.98,
    method: "automatic",
    metricBase: 44_000,
  },
  {
    id: seedId(632),
    contentKey: "succession",
    sourceKey: "max",
    nativeId: "max-succession",
    title: "Succession",
    confidence: 1,
    method: "external_id",
    metricBase: 88_000,
  },
  {
    id: seedId(633),
    contentKey: "severance",
    sourceKey: "apple",
    nativeId: "atv-severance",
    title: "Severance (2022)",
    confidence: 1,
    method: "external_id",
    metricBase: 96_000,
  },
  {
    id: seedId(634),
    contentKey: "moana",
    sourceKey: "disney",
    nativeId: "dp-moana",
    title: "Moana",
    confidence: 1,
    method: "external_id",
    metricBase: 72_000,
  },
  {
    id: seedId(635),
    contentKey: "moana",
    sourceKey: "prime",
    nativeId: "pv-vaiana",
    title: "Vaiana",
    confidence: 0.96,
    method: "automatic",
    metricBase: 18_000,
  },
  {
    id: seedId(636),
    contentKey: "moana2",
    sourceKey: "disney",
    nativeId: "dp-moana-2",
    title: "Moana 2",
    confidence: 1,
    method: "external_id",
    metricBase: 121_000,
  },
  {
    id: seedId(637),
    contentKey: "parks",
    sourceKey: "nbc",
    nativeId: "nbc-parks-syndication",
    title: "Parks and Recreation",
    confidence: 1,
    method: "external_id",
    metricBase: 37_000,
  },
];

export const pendingSampleEntities = [
  {
    id: seedId(603),
    sourceKey: "hulu",
    nativeId: "hu-office",
    title: "The Office",
    type: "series",
    year: null,
    country: null,
    candidateKeys: ["officeUs", "officeUk"] as SampleContentKey[],
    scores: [0.85, 0.85],
  },
  {
    id: seedId(638),
    sourceKey: "prime",
    nativeId: "pv-dune-unknown",
    title: "Dune",
    type: "movie",
    year: null,
    country: "US",
    candidateKeys: ["dune2021", "dune1984"] as SampleContentKey[],
    scores: [0.8, 0.8],
  },
  {
    id: seedId(639),
    sourceKey: "hulu",
    nativeId: "hu-fargo",
    title: "Fargo",
    type: "title",
    year: null,
    country: "US",
    candidateKeys: ["fargoSeries", "fargoFilm"] as SampleContentKey[],
    scores: [0.75, 0.75],
  },
] as const;

export const unresolvedSampleEntity = {
  id: seedId(607),
  sourceKey: "hulu",
  nativeId: "hu-office-hours",
  title: "Office Hours",
  type: "movie",
  year: 2024,
  country: "US",
} as const;

export const sampleTitleByKey = Object.fromEntries(
  sampleTitles.map((title) => [title.key, title]),
) as Record<SampleContentKey, SampleTitle>;

export const sampleSourceByKey = Object.fromEntries(
  sampleSources.map((source) => [source.key, source]),
) as Record<SampleSourceKey, (typeof sampleSources)[number]>;

export const samplePlatformByKey = Object.fromEntries(
  samplePlatforms.map((platform) => [platform.key, platform]),
) as Record<SampleSourceKey, (typeof samplePlatforms)[number]>;
